CREATE TABLE `international_schools` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`country` varchar(128) NOT NULL,
	`countryCode` varchar(3) NOT NULL,
	`city` varchar(128) NOT NULL,
	`region` varchar(128),
	`address` varchar(512),
	`phone` varchar(30),
	`website` varchar(512),
	`email` varchar(320),
	`description` text,
	`missionStatement` text,
	`primaryLanguage` varchar(64) NOT NULL,
	`secondaryLanguage` varchar(64),
	`curriculumType` enum('american','british','ib','national','hybrid','other') NOT NULL DEFAULT 'other',
	`gradeStart` varchar(10),
	`gradeEnd` varchar(10),
	`intlProgramType` enum('day_school','boarding','hybrid','online') NOT NULL DEFAULT 'day_school',
	`missionAffiliation` varchar(255),
	`denomination` varchar(128),
	`accreditation` varchar(255),
	`statementOfFaith` text,
	`tuitionRange` varchar(128),
	`enrollment` int,
	`studentTeacherRatio` varchar(20),
	`yearFounded` int,
	`acceptsExpats` boolean DEFAULT true,
	`visaSupport` boolean DEFAULT false,
	`hasBoarding` boolean DEFAULT false,
	`hasSports` boolean DEFAULT false,
	`hasArts` boolean DEFAULT false,
	`hasESL` boolean DEFAULT false,
	`logoUrl` varchar(512),
	`coverImageUrl` varchar(512),
	`galleryImages` text,
	`contactName` varchar(255),
	`contactTitle` varchar(128),
	`contactEmail` varchar(320),
	`isPremium` boolean NOT NULL DEFAULT false,
	`isApproved` boolean NOT NULL DEFAULT false,
	`featured` boolean NOT NULL DEFAULT false,
	`ownerId` int,
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `international_schools_id` PRIMARY KEY(`id`),
	CONSTRAINT `international_schools_slug_unique` UNIQUE(`slug`)
);
