// School Choice Programs Data - Auto-generated from CSV
// All 50 states + territories with school choice program information

export interface SchoolChoiceProgram {
  state: string;
  programName: string;
  type: string;
  supports: string;
  link: string;
  description: string;
  priority: 'High' | 'Medium' | 'Low';
  notes: string;
}

export const schoolChoicePrograms: SchoolChoiceProgram[] = [
  {
    state: 'Alabama',
    programName: 'CHOOSE Act',
    type: 'Education Savings Account',
    supports: 'Private school / homeschool',
    link: 'https://www.revenue.alabama.gov/individual-corporate/the-choose-act/',
    description: 'K-12 students. Private school awards and homeschool awards available. Priority rules and income limits may apply depending on year.',
    priority: 'High',
    notes: 'Use for Christian school and homeschool funding page.',
  },
  {
    state: 'Alabama',
    programName: 'Accountability Act Parent-Taxpayer Refundable Tax Credits',
    type: 'Refundable Tax Credit',
    supports: 'Private school',
    link: 'https://www.revenue.alabama.gov/',
    description: 'Eligible families moving students from failing schools or meeting state criteria. Verify annually with Alabama Department of Revenue.',
    priority: 'Medium',
    notes: 'Good secondary program mention.',
  },
  {
    state: 'Alabama',
    programName: 'Alabama Education Scholarship Program',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://www.revenue.alabama.gov/',
    description: 'Scholarships funded by tax-credit donations through scholarship granting organizations. Eligibility varies by income and school participation.',
    priority: 'Medium',
    notes: 'List under scholarship options.',
  },
  {
    state: 'Alaska',
    programName: 'Correspondence School Allotment Program',
    type: 'Public allotment / homeschool support',
    supports: 'Homeschool / courses',
    link: 'https://education.alaska.gov/',
    description: 'Families enrolled in approved correspondence programs may receive allotments for approved educational services. Rules vary by district/program.',
    priority: 'Medium',
    notes: 'Useful homeschool resource, not a traditional voucher.',
  },
  {
    state: 'Arizona',
    programName: 'Empowerment Scholarship Account',
    type: 'Education Savings Account',
    supports: 'Private school / homeschool',
    link: 'https://www.azed.gov/esa',
    description: 'Arizona students who meet ESA rules. Program is broadly available and commonly used for private school and homeschool expenses.',
    priority: 'High',
    notes: 'Major Christian school funding program.',
  },
  {
    state: 'Arizona',
    programName: 'Individual School Tuition Organization Tax Credit',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://azdor.gov/tax-credits/school-tax-credits',
    description: 'Scholarships funded through school tuition organizations. Eligibility and award size vary by STO.',
    priority: 'High',
    notes: 'Add STO explainer page.',
  },
  {
    state: 'Arizona',
    programName: 'Low-Income Corporate School Tuition Organization Tax Credit',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://azdor.gov/tax-credits/school-tax-credits',
    description: 'Scholarships for eligible low-income students through certified school tuition organizations.',
    priority: 'High',
    notes: 'Useful for family financial aid page.',
  },
  {
    state: 'Arizona',
    programName: 'Switcher Individual School Tuition Organization Tax Credit',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://azdor.gov/tax-credits/school-tax-credits',
    description: 'Scholarships for students switching from public school or meeting program-specific conditions.',
    priority: 'High',
    notes: 'Mention as private school scholarship path.',
  },
  {
    state: 'Arizona',
    programName: 'Disabled/Displaced Corporate School Tuition Organization Tax Credit',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://azdor.gov/tax-credits/school-tax-credits',
    description: 'Scholarships for students with disabilities or students in foster/displaced circumstances.',
    priority: 'High',
    notes: 'Important special-needs support.',
  },
  {
    state: 'Arkansas',
    programName: 'Children’s Educational Freedom Account Program',
    type: 'Education Savings Account',
    supports: 'Private school / homeschool',
    link: 'https://dese.ade.arkansas.gov/Offices/communications/school-choice-and-parent-empowerment',
    description: 'Arkansas K-12 students. Funds can be used for approved expenses including private school tuition and homeschool curriculum.',
    priority: 'High',
    notes: 'Strong page for Christian school choice.',
  },
  {
    state: 'Arkansas',
    programName: 'Philanthropic Investment in Arkansas Kids Scholarship Program',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://dese.ade.arkansas.gov/',
    description: 'Scholarship program funded by donor tax credits. Eligibility varies by family and participating organization.',
    priority: 'Medium',
    notes: 'Secondary scholarship listing.',
  },
  {
    state: 'California',
    programName: 'No statewide private school choice program',
    type: 'None',
    supports: 'N/A',
    link: 'https://www.cde.ca.gov/',
    description: 'No statewide ESA, voucher, or private-school tax-credit scholarship program identified.',
    priority: 'High',
    notes: 'Still create state page with \'No current voucher program\' and alternatives.',
  },
  {
    state: 'Colorado',
    programName: 'No statewide private school choice program',
    type: 'None',
    supports: 'N/A',
    link: 'https://www.cde.state.co.us/',
    description: 'No statewide ESA, voucher, or private-school tax-credit scholarship program identified.',
    priority: 'High',
    notes: 'Use for SEO and explain private school financial aid.',
  },
  {
    state: 'Connecticut',
    programName: 'No statewide private school choice program',
    type: 'None',
    supports: 'N/A',
    link: 'https://portal.ct.gov/sde',
    description: 'No statewide ESA, voucher, or private-school tax-credit scholarship program identified.',
    priority: 'High',
    notes: 'Create informational page.',
  },
  {
    state: 'Delaware',
    programName: 'No statewide private school choice program',
    type: 'None',
    supports: 'N/A',
    link: 'https://education.delaware.gov/',
    description: 'No statewide ESA, voucher, or private-school tax-credit scholarship program identified.',
    priority: 'High',
    notes: 'Create informational page.',
  },
  {
    state: 'Florida',
    programName: 'Family Empowerment Scholarship for Educational Options',
    type: 'Education Savings Account',
    supports: 'Private school',
    link: 'https://www.fldoe.org/schools/school-choice/k-12-scholarship-programs/',
    description: 'Florida K-12 students. Universal-style private school scholarship; specific award and process handled by scholarship funding organizations.',
    priority: 'High',
    notes: 'Top priority for Find Christian Schools.',
  },
  {
    state: 'Florida',
    programName: 'Family Empowerment Scholarship for Students with Unique Abilities',
    type: 'Education Savings Account',
    supports: 'Special needs / private school / services',
    link: 'https://www.fldoe.org/schools/school-choice/k-12-scholarship-programs/',
    description: 'Florida students with qualifying special needs. Funds can support private school and approved educational services.',
    priority: 'High',
    notes: 'Important parent search category.',
  },
  {
    state: 'Florida',
    programName: 'Florida Tax Credit Scholarship',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school / transportation',
    link: 'https://www.fldoe.org/schools/school-choice/k-12-scholarship-programs/',
    description: 'Florida K-12 students. Private school scholarship and transportation options available through approved scholarship organizations.',
    priority: 'High',
    notes: 'Use \'Apply through Step Up or AAA\' after verification.',
  },
  {
    state: 'Georgia',
    programName: 'Georgia Promise Scholarship',
    type: 'Education Savings Account',
    supports: 'Private school / approved expenses',
    link: 'https://mygeorgiapromise.org/',
    description: 'Eligible Georgia students in lower-performing public school attendance zones. Funds support qualified education expenses.',
    priority: 'High',
    notes: 'Add as featured Georgia funding.',
  },
  {
    state: 'Georgia',
    programName: 'Georgia Special Needs Scholarship Program',
    type: 'Voucher',
    supports: 'Special needs / private school',
    link: 'https://www.gadoe.org/External-Affairs-and-Policy/Policy/Pages/Special-Needs-Scholarship-Program.aspx',
    description: 'Georgia students with qualifying special needs and prior public school attendance requirements may qualify.',
    priority: 'High',
    notes: 'Special-needs filter.',
  },
  {
    state: 'Georgia',
    programName: 'Qualified Education Expense Tax Credit',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://dor.georgia.gov/qualified-education-expense-tax-credit',
    description: 'Scholarships funded by tax-credit donations through student scholarship organizations. Eligibility varies by SSO.',
    priority: 'High',
    notes: 'Good donor and family explainer.',
  },
  {
    state: 'Hawaii',
    programName: 'No statewide private school choice program',
    type: 'None',
    supports: 'N/A',
    link: 'https://www.hawaiipublicschools.org/',
    description: 'No statewide ESA, voucher, or private-school tax-credit scholarship program identified.',
    priority: 'High',
    notes: 'Create informational page.',
  },
  {
    state: 'Idaho',
    programName: 'Idaho Parental Choice Tax Credit',
    type: 'Refundable Tax Credit',
    supports: 'Private school / homeschool',
    link: 'https://tax.idaho.gov/',
    description: 'Refundable tax credit for qualified education expenses. Verify current rules and application timing with Idaho Tax Commission.',
    priority: 'Medium',
    notes: 'Newer program, verify yearly.',
  },
  {
    state: 'Illinois',
    programName: 'Tax Credits for Educational Expenses',
    type: 'Individual Tax Credit',
    supports: 'Private school / homeschool expenses',
    link: 'https://tax.illinois.gov/',
    description: 'Illinois parents may claim a credit for qualifying K-12 education expenses, subject to state rules and limits.',
    priority: 'Medium',
    notes: 'Not a voucher, but useful parent benefit.',
  },
  {
    state: 'Indiana',
    programName: 'Indiana Choice Scholarship Program',
    type: 'Voucher',
    supports: 'Private school',
    link: 'https://www.in.gov/doe/students/indiana-choice-scholarship-program/',
    description: 'Indiana K-12 students meeting state eligibility rules. Program has broad eligibility compared with many states.',
    priority: 'High',
    notes: 'Major Christian school funding program.',
  },
  {
    state: 'Indiana',
    programName: 'Indiana Education Scholarship Account Program',
    type: 'Education Savings Account',
    supports: 'Special needs / approved expenses',
    link: 'https://www.in.gov/tos/inesa/',
    description: 'Students with qualifying disabilities may use funds for approved educational services and private school options.',
    priority: 'High',
    notes: 'Special-needs category.',
  },
  {
    state: 'Indiana',
    programName: 'Indiana School Scholarship Tax Credit',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://www.in.gov/dor/tax-forms/individual-income-tax-forms/school-scholarship-tax-credit/',
    description: 'Scholarships funded through scholarship granting organizations. Eligibility varies by SGO and family income.',
    priority: 'Medium',
    notes: 'Secondary scholarship option.',
  },
  {
    state: 'Indiana',
    programName: 'Private School/Homeschool Deduction',
    type: 'Tax Deduction',
    supports: 'Private school / homeschool',
    link: 'https://www.in.gov/dor/',
    description: 'Indiana families may deduct qualifying private school or homeschool expenses up to state limits.',
    priority: 'Medium',
    notes: 'Add as parent tax benefit.',
  },
  {
    state: 'Iowa',
    programName: 'Students First Education Savings Account',
    type: 'Education Savings Account',
    supports: 'Private school',
    link: 'https://educate.iowa.gov/pk-12/educational-choice/students-first-education-savings-accounts',
    description: 'Iowa K-12 students attending accredited nonpublic schools. Universal phase-in completed under state rules.',
    priority: 'High',
    notes: 'Major Christian school funding program.',
  },
  {
    state: 'Iowa',
    programName: 'Iowa School Tuition Organization Tax Credit',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://tax.iowa.gov/',
    description: 'Scholarships funded by donations to school tuition organizations. Eligibility varies by income and STO.',
    priority: 'Medium',
    notes: 'Useful secondary financial aid option.',
  },
  {
    state: 'Iowa',
    programName: 'Tuition and Textbook Tax Credit',
    type: 'Individual Tax Credit',
    supports: 'Private school / homeschool expenses',
    link: 'https://tax.iowa.gov/',
    description: 'Iowa families may claim credit for qualifying tuition and textbook expenses, subject to state limits.',
    priority: 'Medium',
    notes: 'Good parent benefit listing.',
  },
  {
    state: 'Kansas',
    programName: 'Tax Credit for Low Income Students Scholarship Program',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://www.ksde.org/Agency/Fiscal-and-Administrative-Services/School-Finance/Tax-Credit-for-Low-Income-Students-Scholarship-Program',
    description: 'Eligible low-income students can receive scholarships to attend participating private schools.',
    priority: 'High',
    notes: 'Straightforward scholarship page.',
  },
  {
    state: 'Kentucky',
    programName: 'No statewide private school choice program',
    type: 'None',
    supports: 'N/A',
    link: 'https://www.education.ky.gov/',
    description: 'No statewide ESA, voucher, or private-school tax-credit scholarship program identified.',
    priority: 'High',
    notes: 'Informational page only.',
  },
  {
    state: 'Louisiana',
    programName: 'LA GATOR Scholarship Program',
    type: 'Education Savings Account',
    supports: 'Private school / approved expenses',
    link: 'https://louisianagator.la.gov/',
    description: 'Louisiana students may qualify for ESA funds under priority and income rules as program phases in.',
    priority: 'High',
    notes: 'Major new Louisiana opportunity.',
  },
  {
    state: 'Louisiana',
    programName: 'School Choice Program for Certain Students with Exceptionalities',
    type: 'Voucher',
    supports: 'Special needs / private school',
    link: 'https://www.louisianabelieves.com/schools/school-choice',
    description: 'Louisiana students with qualifying exceptionalities may qualify for private-school scholarship support.',
    priority: 'High',
    notes: 'Special-needs filter.',
  },
  {
    state: 'Louisiana',
    programName: 'Tuition Donation Credit Program',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://www.louisianabelieves.com/schools/school-choice',
    description: 'Scholarships funded through school tuition organizations. Eligibility varies by STO and family circumstances.',
    priority: 'Medium',
    notes: 'Secondary scholarship listing.',
  },
  {
    state: 'Louisiana',
    programName: 'Elementary and Secondary School Tuition Deduction',
    type: 'Tax Deduction',
    supports: 'Private school / homeschool',
    link: 'https://revenue.louisiana.gov/',
    description: 'Louisiana taxpayers may deduct eligible education expenses subject to state rules.',
    priority: 'Medium',
    notes: 'Parent tax benefit.',
  },
  {
    state: 'Maine',
    programName: 'Town Tuitioning Program',
    type: 'Voucher / Town Tuitioning',
    supports: 'Private school in eligible towns',
    link: 'https://www.maine.gov/doe/learning/schools/schoolchoice',
    description: 'Students in towns without a public school may receive tuition support to attend another public or approved private school.',
    priority: 'High',
    notes: 'Not statewide for everyone, but valuable.',
  },
  {
    state: 'Maryland',
    programName: 'BOOST Program',
    type: 'Voucher',
    supports: 'Private school',
    link: 'https://marylandpublicschools.org/Pages/boost/index.aspx',
    description: 'Scholarships for eligible low-income students to attend participating nonpublic schools.',
    priority: 'High',
    notes: 'Use for Christian schools in Maryland.',
  },
  {
    state: 'Massachusetts',
    programName: 'No statewide private school choice program',
    type: 'None',
    supports: 'N/A',
    link: 'https://www.doe.mass.edu/',
    description: 'No statewide ESA, voucher, or private-school tax-credit scholarship program identified.',
    priority: 'High',
    notes: 'Informational page only.',
  },
  {
    state: 'Michigan',
    programName: 'No statewide private school choice program',
    type: 'None',
    supports: 'N/A',
    link: 'https://www.michigan.gov/mde',
    description: 'No statewide ESA, voucher, or private-school tax-credit scholarship program identified.',
    priority: 'High',
    notes: 'State constitution restrictions make this important to explain.',
  },
  {
    state: 'Minnesota',
    programName: 'K-12 Education Credit',
    type: 'Individual Tax Credit',
    supports: 'Education expenses',
    link: 'https://www.revenue.state.mn.us/k-12-education-subtraction-and-credit',
    description: 'Eligible families may claim a credit for qualifying K-12 education expenses subject to income and expense rules.',
    priority: 'High',
    notes: 'Useful parent benefit.',
  },
  {
    state: 'Minnesota',
    programName: 'K-12 Education Subtraction',
    type: 'Tax Deduction',
    supports: 'Education expenses',
    link: 'https://www.revenue.state.mn.us/k-12-education-subtraction-and-credit',
    description: 'Families may subtract qualifying K-12 education expenses from Minnesota taxable income.',
    priority: 'High',
    notes: 'Use with credit explanation.',
  },
  {
    state: 'Mississippi',
    programName: 'Equal Opportunity for Students with Special Needs Program',
    type: 'Education Savings Account',
    supports: 'Special needs / private school',
    link: 'https://www.mdek12.org/OSA/ESA',
    description: 'Eligible Mississippi students with special needs may receive ESA funds for private school and approved education services.',
    priority: 'High',
    notes: 'Special-needs page.',
  },
  {
    state: 'Mississippi',
    programName: 'Dyslexia Therapy Scholarship',
    type: 'Voucher',
    supports: 'Dyslexia / private therapy school',
    link: 'https://www.mdek12.org/',
    description: 'Students with dyslexia who meet criteria may receive scholarship support for approved schools/services.',
    priority: 'Medium',
    notes: 'Specialized filter.',
  },
  {
    state: 'Mississippi',
    programName: 'Nate Rogers Scholarship',
    type: 'Voucher',
    supports: 'Speech-language impairment',
    link: 'https://www.mdek12.org/',
    description: 'Students with speech-language impairment may qualify for scholarship support under state rules.',
    priority: 'Medium',
    notes: 'Specialized filter.',
  },
  {
    state: 'Missouri',
    programName: 'MOScholars',
    type: 'Tax-Credit Education Savings Account',
    supports: 'Private school / homeschool / approved expenses',
    link: 'https://treasurer.mo.gov/MOScholars/',
    description: 'Eligible Missouri students may receive ESA-style scholarships funded by tax-credit donations.',
    priority: 'High',
    notes: 'Good for private and homeschool page.',
  },
  {
    state: 'Montana',
    programName: 'Special Needs Equal Opportunity Education Savings Account',
    type: 'Education Savings Account',
    supports: 'Special needs',
    link: 'https://opi.mt.gov/',
    description: 'Students with qualifying special needs may receive ESA funds under state rules.',
    priority: 'Medium',
    notes: 'Verify official annual status.',
  },
  {
    state: 'Montana',
    programName: 'Montana Tax Credit Scholarship Program',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://mtrevenue.gov/',
    description: 'Scholarships funded by tax-credit donations to student scholarship organizations.',
    priority: 'Medium',
    notes: 'Useful scholarship option.',
  },
  {
    state: 'Nebraska',
    programName: 'No statewide private school choice program',
    type: 'None',
    supports: 'N/A',
    link: 'https://www.education.ne.gov/',
    description: 'No active statewide private school choice program identified after repeal activity. Verify if legislation changes.',
    priority: 'Medium',
    notes: 'Monitor for legal/policy updates.',
  },
  {
    state: 'Nevada',
    programName: 'Educational Choice Scholarship Program',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://doe.nv.gov/',
    description: 'Scholarships funded by tax-credit donations to scholarship organizations for eligible students.',
    priority: 'Medium',
    notes: 'Good scholarship page.',
  },
  {
    state: 'Nevada',
    programName: 'Federal Tax Credit Scholarship Program',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://doe.nv.gov/',
    description: 'New federal tax credit scholarship program (2026) for eligible Nevada students attending private schools. Funded through federal tax credits.',
    priority: 'High',
    notes: 'New program - verify eligibility and application process.',
  },
  {
    state: 'New Hampshire',
    programName: 'Education Freedom Account',
    type: 'Education Savings Account',
    supports: 'Private school / homeschool / approved expenses',
    link: 'https://www.education.nh.gov/pathways-education/education-freedom-accounts',
    description: 'Eligible New Hampshire students may use ESA funds for private school, homeschool materials, tutoring and other approved expenses.',
    priority: 'High',
    notes: 'Strong homeschool and Christian school opportunity.',
  },
  {
    state: 'New Hampshire',
    programName: 'Education Tax Credit Program',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school / homeschool',
    link: 'https://www.education.nh.gov/',
    description: 'Scholarships funded by tax-credit donations. Eligibility varies by scholarship organization.',
    priority: 'Medium',
    notes: 'Secondary scholarship listing.',
  },
  {
    state: 'New Hampshire',
    programName: 'Town Tuitioning Program',
    type: 'Voucher / Town Tuitioning',
    supports: 'Private school in eligible towns',
    link: 'https://www.education.nh.gov/',
    description: 'Students in towns without assigned public schools may receive tuition support to attend other schools.',
    priority: 'Medium',
    notes: 'Location-specific benefit.',
  },
  {
    state: 'New Jersey',
    programName: 'No statewide private school choice program',
    type: 'None',
    supports: 'N/A',
    link: 'https://www.nj.gov/education/',
    description: 'No statewide ESA, voucher, or private-school tax-credit scholarship program identified.',
    priority: 'High',
    notes: 'Informational page only.',
  },
  {
    state: 'New Mexico',
    programName: 'No statewide private school choice program',
    type: 'None',
    supports: 'N/A',
    link: 'https://webnew.ped.state.nm.us/',
    description: 'No statewide ESA, voucher, or private-school tax-credit scholarship program identified.',
    priority: 'High',
    notes: 'Informational page only.',
  },
  {
    state: 'New York',
    programName: 'No statewide private school choice program',
    type: 'None',
    supports: 'N/A',
    link: 'https://www.nysed.gov/',
    description: 'No statewide ESA, voucher, or private-school tax-credit scholarship program identified.',
    priority: 'High',
    notes: 'Informational page only.',
  },
  {
    state: 'North Carolina',
    programName: 'Opportunity Scholarship',
    type: 'Voucher',
    supports: 'Private school',
    link: 'https://www.ncseaa.edu/k12/opportunity/',
    description: 'North Carolina students may qualify for private school scholarships based on state rules and funding tiers.',
    priority: 'High',
    notes: 'Major Christian school funding program.',
  },
  {
    state: 'North Carolina',
    programName: 'Education Student Accounts Plus (ESA+)',
    type: 'Education Savings Account',
    supports: 'Special needs / private school / services',
    link: 'https://www.ncseaa.edu/k12/esa/',
    description: 'Eligible students with disabilities may use funds for private school tuition and approved educational services.',
    priority: 'High',
    notes: 'Special-needs page.',
  },
  {
    state: 'North Dakota',
    programName: 'No statewide private school choice program',
    type: 'None',
    supports: 'N/A',
    link: 'https://www.nd.gov/dpi/',
    description: 'No statewide ESA, voucher, or private-school tax-credit scholarship program identified.',
    priority: 'High',
    notes: 'Informational page only.',
  },
  {
    state: 'Ohio',
    programName: 'EdChoice Scholarship Program',
    type: 'Voucher',
    supports: 'Private school',
    link: 'https://education.ohio.gov/Topics/Other-Resources/Scholarships/EdChoice-Scholarship-Program',
    description: 'Ohio students may qualify for private school scholarships under traditional or expansion rules.',
    priority: 'High',
    notes: 'Major voucher program.',
  },
  {
    state: 'Ohio',
    programName: 'Cleveland Scholarship Program',
    type: 'Voucher',
    supports: 'Private school',
    link: 'https://education.ohio.gov/Topics/Other-Resources/Scholarships/Cleveland-Scholarship-Tutoring-Program',
    description: 'Students living in Cleveland Municipal School District may receive scholarships for private school.',
    priority: 'High',
    notes: 'Local voucher page.',
  },
  {
    state: 'Ohio',
    programName: 'Autism Scholarship Program',
    type: 'Voucher',
    supports: 'Autism / services / private provider',
    link: 'https://education.ohio.gov/Topics/Other-Resources/Scholarships/Autism-Scholarship-Program',
    description: 'Students with autism and an IEP may qualify for scholarship funds for approved providers.',
    priority: 'High',
    notes: 'Special-needs filter.',
  },
  {
    state: 'Ohio',
    programName: 'Jon Peterson Special Needs Scholarship',
    type: 'Voucher',
    supports: 'Special needs / services',
    link: 'https://education.ohio.gov/Topics/Other-Resources/Scholarships/Special-Needs-Scholarship',
    description: 'Students with an IEP may qualify for funds to attend approved special education providers.',
    priority: 'High',
    notes: 'Special-needs filter.',
  },
  {
    state: 'Ohio',
    programName: 'Ohio K-12 Home Education Tax Credit',
    type: 'Tax Credit',
    supports: 'Homeschool',
    link: 'https://tax.ohio.gov/',
    description: 'Ohio homeschool families may claim eligible home education expenses subject to state rules and limits.',
    priority: 'Medium',
    notes: 'Homeschool benefit.',
  },
  {
    state: 'Oklahoma',
    programName: 'Parental Choice Tax Credit',
    type: 'Refundable Tax Credit',
    supports: 'Private school / homeschool',
    link: 'https://www.parentalchoice.ok.gov/',
    description: 'Eligible Oklahoma families may receive refundable tax credits for private school tuition and homeschool expenses.',
    priority: 'High',
    notes: 'Major parent-facing program.',
  },
  {
    state: 'Oklahoma',
    programName: 'Lindsey Nicole Henry Scholarship',
    type: 'Voucher',
    supports: 'Special needs / foster / military',
    link: 'https://sde.ok.gov/lindsey-nicole-henry-lnh-scholarship-program',
    description: 'Eligible students with disabilities and certain other students may receive scholarship support for private school.',
    priority: 'High',
    notes: 'Special-needs filter.',
  },
  {
    state: 'Oklahoma',
    programName: 'Equal Opportunity Education Scholarship',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://www.sde.ok.gov/',
    description: 'Scholarship funded by tax-credit donations through scholarship granting organizations.',
    priority: 'Medium',
    notes: 'Secondary scholarship option.',
  },
  {
    state: 'Oregon',
    programName: 'No statewide private school choice program',
    type: 'None',
    supports: 'N/A',
    link: 'https://www.oregon.gov/ode/',
    description: 'No statewide ESA, voucher, or private-school tax-credit scholarship program identified.',
    priority: 'High',
    notes: 'Informational page only.',
  },
  {
    state: 'Pennsylvania',
    programName: 'Educational Improvement Tax Credit',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://dced.pa.gov/programs/educational-improvement-tax-credit-program-eitc/',
    description: 'Scholarships funded by business tax-credit donations through approved scholarship organizations.',
    priority: 'High',
    notes: 'Important Pennsylvania scholarship page.',
  },
  {
    state: 'Pennsylvania',
    programName: 'Opportunity Scholarship Tax Credit',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://dced.pa.gov/programs/opportunity-scholarship-tax-credit-program-ostc/',
    description: 'Scholarships funded by tax-credit donations for students in low-achieving school zones.',
    priority: 'High',
    notes: 'Create separate program page.',
  },
  {
    state: 'Puerto Rico',
    programName: 'Free School Selection Program',
    type: 'Voucher',
    supports: 'Private school',
    link: 'https://de.pr.gov/',
    description: 'Voucher-style program supporting eligible students attending participating private schools. Verify active application details locally.',
    priority: 'Medium',
    notes: 'Include in broader U.S. territory directory.',
  },
  {
    state: 'Rhode Island',
    programName: 'Tax Credits for Contributions to Scholarship Organizations',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://ride.ri.gov/',
    description: 'Scholarships funded through tax-credit donations to scholarship organizations.',
    priority: 'Medium',
    notes: 'Scholarship page.',
  },
  {
    state: 'South Carolina',
    programName: 'Education Scholarship Trust Fund',
    type: 'Education Savings Account',
    supports: 'Private school',
    link: 'https://www.scstudentconnection.org/',
    description: 'Eligible South Carolina students may receive ESA funds for private school tuition and qualified expenses.',
    priority: 'High',
    notes: 'Major program.',
  },
  {
    state: 'South Carolina',
    programName: 'Exceptional SC / Tax-Credit Scholarship',
    type: 'Tax-Credit Scholarship',
    supports: 'Special needs / private school',
    link: 'https://exceptionalsc.org/',
    description: 'Scholarships for eligible students with exceptional needs through tax-credit funded donations.',
    priority: 'High',
    notes: 'Special-needs program.',
  },
  {
    state: 'South Carolina',
    programName: 'Refundable Educational Credit',
    type: 'Refundable Tax Credit',
    supports: 'Private school',
    link: 'https://dor.sc.gov/',
    description: 'Eligible families may qualify for refundable credits related to private school expenses under state rules.',
    priority: 'Medium',
    notes: 'Verify yearly.',
  },
  {
    state: 'South Dakota',
    programName: 'Partners in Education Tax Credit Program',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://doe.sd.gov/',
    description: 'Scholarships funded by insurance-company tax-credit donations for eligible students.',
    priority: 'Medium',
    notes: 'Scholarship listing.',
  },
  {
    state: 'Tennessee',
    programName: 'Education Freedom Scholarship',
    type: 'Education Savings Account',
    supports: 'Private school',
    link: 'https://www.tn.gov/education/families/school-options/education-freedom-scholarships.html',
    description: 'Eligible Tennessee students may receive scholarship funds for private school as program expands.',
    priority: 'High',
    notes: 'Major new Tennessee program.',
  },
  {
    state: 'Tennessee',
    programName: 'Individualized Education Account Program',
    type: 'Education Savings Account',
    supports: 'Special needs',
    link: 'https://www.tn.gov/education/families/school-options/individualized-education-account-program.html',
    description: 'Eligible students with disabilities may receive funds for private school and approved services.',
    priority: 'High',
    notes: 'Special-needs page.',
  },
  {
    state: 'Tennessee',
    programName: 'Education Savings Account Pilot Program',
    type: 'Education Savings Account',
    supports: 'Private school in eligible districts',
    link: 'https://www.tn.gov/education/families/school-options/education-savings-account-program.html',
    description: 'Eligible students in Memphis, Nashville and/or qualifying districts may apply under pilot rules.',
    priority: 'High',
    notes: 'Location-specific.',
  },
  {
    state: 'Texas',
    programName: 'Texas Education Savings Account Program',
    type: 'Education Savings Account',
    supports: 'Private school / approved expenses',
    link: 'https://tea.texas.gov/',
    description: 'Texas ESA program is scheduled for rollout. Families should verify application timing and eligibility with TEA.',
    priority: 'Medium',
    notes: 'Create \'coming soon/2026\' page and monitor.',
  },
  {
    state: 'Utah',
    programName: 'Utah Fits All Scholarship',
    type: 'Education Savings Account',
    supports: 'Private school / homeschool / approved expenses',
    link: 'https://ufascholarship.com/',
    description: 'Eligible Utah K-12 students may apply for scholarship funds usable for tuition and approved education expenses.',
    priority: 'High',
    notes: 'Major universal-style program.',
  },
  {
    state: 'Utah',
    programName: 'Carson Smith Scholarship',
    type: 'Voucher',
    supports: 'Special needs / private school',
    link: 'https://schools.utah.gov/specialeducation/programs/carsonsmithscholarship',
    description: 'Eligible students with disabilities may receive scholarships to attend approved private schools.',
    priority: 'High',
    notes: 'Special-needs program.',
  },
  {
    state: 'Utah',
    programName: 'Special Needs Opportunity Scholarship',
    type: 'Tax-Credit ESA',
    supports: 'Special needs',
    link: 'https://schools.utah.gov/',
    description: 'Students with qualifying special needs may receive scholarship support through approved organizations.',
    priority: 'Medium',
    notes: 'Verify official program administrator.',
  },
  {
    state: 'Vermont',
    programName: 'Town Tuitioning Program',
    type: 'Voucher / Town Tuitioning',
    supports: 'Private school in eligible towns',
    link: 'https://education.vermont.gov/vermont-schools/school-operations/public-schools/public-tuitioning',
    description: 'Students in towns without public schools may receive tuition support to attend approved public or private schools.',
    priority: 'High',
    notes: 'Location-specific, important for rural families.',
  },
  {
    state: 'Virginia',
    programName: 'Education Improvement Scholarships Tax Credits Program',
    type: 'Tax-Credit Scholarship',
    supports: 'Private school',
    link: 'https://www.doe.virginia.gov/parents-students/for-parents/school-choice/education-improvement-scholarships-tax-credits-program',
    description: 'Scholarships funded by tax-credit donations for eligible students attending participating private schools.',
    priority: 'High',
    notes: 'Good scholarship page.',
  },
  {
    state: 'Washington',
    programName: 'No statewide private school choice program',
    type: 'None',
    supports: 'N/A',
    link: 'https://ospi.k12.wa.us/',
    description: 'No statewide ESA, voucher, or private-school tax-credit scholarship program identified.',
    priority: 'High',
    notes: 'Informational page only.',
  },
  {
    state: 'Washington D.C.',
    programName: 'D.C. Opportunity Scholarship Program',
    type: 'Voucher',
    supports: 'Private school',
    link: 'https://servingourchildrendc.org/',
    description: 'Eligible low-income D.C. students may receive scholarships to attend participating private schools.',
    priority: 'High',
    notes: 'Important voucher page.',
  },
  {
    state: 'West Virginia',
    programName: 'Hope Scholarship',
    type: 'Education Savings Account',
    supports: 'Private school / homeschool / approved expenses',
    link: 'https://hopescholarshipwv.com/',
    description: 'Eligible West Virginia students may receive ESA funds for private school, homeschool curriculum and approved services.',
    priority: 'High',
    notes: 'Major Christian/homeschool opportunity.',
  },
  {
    state: 'Wisconsin',
    programName: 'Milwaukee Parental Choice Program',
    type: 'Voucher',
    supports: 'Private school in Milwaukee',
    link: 'https://dpi.wi.gov/parental-education-options/choice-programs',
    description: 'Eligible Milwaukee students may receive private school vouchers.',
    priority: 'High',
    notes: 'Local voucher page.',
  },
  {
    state: 'Wisconsin',
    programName: 'Racine Parental Choice Program',
    type: 'Voucher',
    supports: 'Private school in Racine',
    link: 'https://dpi.wi.gov/parental-education-options/choice-programs',
    description: 'Eligible Racine students may receive private school vouchers.',
    priority: 'High',
    notes: 'Local voucher page.',
  },
  {
    state: 'Wisconsin',
    programName: 'Wisconsin Parental Choice Program',
    type: 'Voucher',
    supports: 'Private school statewide',
    link: 'https://dpi.wi.gov/parental-education-options/choice-programs',
    description: 'Eligible students outside Milwaukee/Racine may receive private school vouchers.',
    priority: 'High',
    notes: 'Statewide voucher page.',
  },
  {
    state: 'Wisconsin',
    programName: 'Special Needs Scholarship Program',
    type: 'Voucher',
    supports: 'Special needs / private school',
    link: 'https://dpi.wi.gov/parental-education-options/special-needs-scholarship-program',
    description: 'Eligible students with disabilities may receive scholarships to attend participating private schools.',
    priority: 'High',
    notes: 'Special-needs page.',
  },
  {
    state: 'Wisconsin',
    programName: 'K-12 Private School Tuition Deduction',
    type: 'Tax Deduction',
    supports: 'Private school',
    link: 'https://www.revenue.wi.gov/',
    description: 'Wisconsin taxpayers may deduct eligible private school tuition subject to state rules and limits.',
    priority: 'Medium',
    notes: 'Parent tax benefit.',
  },
  {
    state: 'Wyoming',
    programName: 'Steamboat Legacy Scholarship Act',
    type: 'Education Savings Account',
    supports: 'Private school / approved expenses',
    link: 'https://edu.wyoming.gov/',
    description: 'Eligible Wyoming families may receive ESA funds under program rules. Verify application status with Wyoming Department of Education.',
    priority: 'Medium',
    notes: 'New/expanding program, monitor annually.',
  },
];

export function getProgramsByState(state: string): SchoolChoiceProgram[] {
  return schoolChoicePrograms.filter(p => p.state === state);
}

export function hasHighPriorityProgram(state: string): boolean {
  return schoolChoicePrograms.some(p => p.state === state && p.priority === 'High' && p.type !== 'None');
}

export function getStatePrograms(state: string) {
  const progs = getProgramsByState(state);
  const highPriority = progs.filter(p => p.priority === 'High' && p.type !== 'None');
  const other = progs.filter(p => p.priority !== 'High' || p.type === 'None');
  return { highPriority, other };
}
